"""Single V2 database baseline.

This is the only schema migration for the clean V2 project. The application
models remain the source of runtime types; this file is the immutable database
bootstrap contract for a fresh deployment.
"""

from __future__ import annotations

from alembic import op


revision = "v2_baseline"
down_revision = None
branch_labels = ("v2",)
depends_on = None


def upgrade() -> None:
    # Keep the complete fresh-install schema in one deterministic migration.
        op.execute("CREATE TYPE projectrole AS ENUM ('viewer', 'investigator', 'approver', 'admin');")
        op.execute("CREATE TYPE runstatus AS ENUM ('queued', 'running', 'awaiting_approval', 'approved', 'rejected', 'completed', 'failed');")
        op.execute("CREATE TYPE approvalstatus AS ENUM ('pending', 'approved', 'rejected');")
        op.execute("CREATE TYPE draftstatus AS ENUM ('draft', 'approved', 'rejected');")
        op.execute("CREATE TYPE evalstatus AS ENUM ('queued', 'running', 'completed', 'failed');")
        op.execute("CREATE TYPE operationalrunstatus AS ENUM ('queued', 'running', 'completed', 'failed');")
        op.execute("CREATE TABLE projects (\n\tid UUID NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\tsettings_json JSONB, \n\tdemo_mode BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_projects PRIMARY KEY (id), \n\tCONSTRAINT uq_projects_name UNIQUE (name)\n);")
        op.execute("CREATE TABLE users (\n\tid UUID NOT NULL, \n\temail VARCHAR(320) NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\tpassword_hash VARCHAR(512) NOT NULL, \n\tpassword_scheme VARCHAR(64), \n\ttoken_version INTEGER NOT NULL, \n\tlast_login_at TIMESTAMP WITH TIME ZONE, \n\tfailed_login_count INTEGER NOT NULL, \n\tdisabled_at TIMESTAMP WITH TIME ZONE, \n\tis_active BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_users PRIMARY KEY (id), \n\tCONSTRAINT uq_users_email UNIQUE (email)\n);")
        op.execute("CREATE TABLE agent_runs (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tuser_id UUID, \n\tuser_query TEXT NOT NULL, \n\ttask_type VARCHAR(128), \n\tstatus runstatus NOT NULL, \n\trisk_level VARCHAR(32), \n\tpending_approval BOOLEAN NOT NULL, \n\tstate_json JSONB, \n\tfinal_answer_json JSONB, \n\terror TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_agent_runs PRIMARY KEY (id), \n\tCONSTRAINT fk_agent_runs_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_agent_runs_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL\n);")
        op.execute("CREATE INDEX ix_agent_runs_project_created ON agent_runs (project_id, created_at);")
        op.execute("CREATE INDEX ix_agent_runs_status_created ON agent_runs (status, created_at);")
        op.execute("CREATE TABLE audit_events (\n\tid UUID NOT NULL, \n\tproject_id UUID, \n\tuser_id UUID, \n\tactor_email TEXT, \n\taction VARCHAR(128) NOT NULL, \n\tresource_type VARCHAR(128), \n\tresource_id TEXT, \n\tstatus VARCHAR(64) NOT NULL, \n\tip_address TEXT, \n\tuser_agent TEXT, \n\tmetadata_json JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_audit_events PRIMARY KEY (id), \n\tCONSTRAINT fk_audit_events_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_audit_events_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL\n);")
        op.execute("CREATE INDEX ix_audit_events_action_created ON audit_events (action, created_at);")
        op.execute("CREATE INDEX ix_audit_events_project_created ON audit_events (project_id, created_at);")
        op.execute("CREATE INDEX ix_audit_events_user_created ON audit_events (user_id, created_at);")
        op.execute("CREATE TABLE collectors (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tname TEXT NOT NULL, \n\tenvironment TEXT, \n\tversion TEXT, \n\tstatus VARCHAR(64) NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_collectors PRIMARY KEY (id), \n\tCONSTRAINT uq_collectors_project_name_environment UNIQUE (project_id, name, environment), \n\tCONSTRAINT fk_collectors_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_collectors_project_id ON collectors (project_id);")
        op.execute("CREATE TABLE eval_runs (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tstatus evalstatus NOT NULL, \n\tsummary_json JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_eval_runs PRIMARY KEY (id), \n\tCONSTRAINT fk_eval_runs_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_eval_runs_project_created ON eval_runs (project_id, created_at);")
        op.execute("CREATE TABLE operational_runs (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\trun_type VARCHAR(64) NOT NULL, \n\tstatus operationalrunstatus NOT NULL, \n\tidempotency_key VARCHAR(128) NOT NULL, \n\trequest_json JSONB, \n\tsummary_json JSONB, \n\tattempts INTEGER NOT NULL, \n\tmodel_call_count INTEGER NOT NULL, \n\tinput_tokens INTEGER NOT NULL, \n\toutput_tokens INTEGER NOT NULL, \n\terror_code VARCHAR(64), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_operational_runs PRIMARY KEY (id), \n\tCONSTRAINT uq_operational_runs_idempotency UNIQUE (project_id, run_type, idempotency_key), \n\tCONSTRAINT fk_operational_runs_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_operational_runs_project_created ON operational_runs (project_id, created_at);")
        op.execute("CREATE INDEX ix_operational_runs_project_type ON operational_runs (project_id, run_type);")
        op.execute("CREATE INDEX ix_operational_runs_status_created ON operational_runs (status, created_at);")
        op.execute("CREATE TABLE project_members (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\trole projectrole NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_project_members PRIMARY KEY (id), \n\tCONSTRAINT uq_project_members_project_user UNIQUE (project_id, user_id), \n\tCONSTRAINT fk_project_members_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_project_members_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_project_members_project_id ON project_members (project_id);")
        op.execute("CREATE INDEX ix_project_members_user_id ON project_members (user_id);")
        op.execute("CREATE TABLE retrieval_runs (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tquery TEXT NOT NULL, \n\trewritten_query TEXT, \n\ttop_k INTEGER NOT NULL, \n\tlatency_ms INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_retrieval_runs PRIMARY KEY (id), \n\tCONSTRAINT fk_retrieval_runs_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n);")
        op.execute("CREATE TABLE sources (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\tsource_type VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(64) NOT NULL, \n\tsync_mode VARCHAR(64) NOT NULL, \n\tsource_uri TEXT, \n\tconfig_json JSONB, \n\tcredentials_ref TEXT, \n\tversion_hash VARCHAR(128), \n\tlast_sync_started_at TIMESTAMP WITH TIME ZONE, \n\tlast_sync_finished_at TIMESTAMP WITH TIME ZONE, \n\tlast_sync_status VARCHAR(64), \n\tlast_error TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tingested_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_sources PRIMARY KEY (id), \n\tCONSTRAINT fk_sources_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_sources_project_id ON sources (project_id);")
        op.execute("CREATE INDEX ix_sources_project_name ON sources (project_id, name);")
        op.execute("CREATE TABLE agent_run_events (\n\tid UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\tsequence_no INTEGER NOT NULL, \n\tevent_type VARCHAR(128) NOT NULL, \n\tnode_name VARCHAR(128), \n\tpayload_json JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_agent_run_events PRIMARY KEY (id), \n\tCONSTRAINT uq_agent_run_events_run_sequence UNIQUE (run_id, sequence_no), \n\tCONSTRAINT fk_agent_run_events_run_id_agent_runs FOREIGN KEY(run_id) REFERENCES agent_runs (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_agent_run_events_run_id ON agent_run_events (run_id);")
        op.execute("CREATE TABLE approvals (\n\tid UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\taction_type VARCHAR(128) NOT NULL, \n\trequested_by_user_id UUID, \n\tresolved_by_user_id UUID, \n\tstatus approvalstatus NOT NULL, \n\trationale TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tresolved_at TIMESTAMP WITH TIME ZONE, \n\tCONSTRAINT pk_approvals PRIMARY KEY (id), \n\tCONSTRAINT fk_approvals_run_id_agent_runs FOREIGN KEY(run_id) REFERENCES agent_runs (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_approvals_requested_by_user_id_users FOREIGN KEY(requested_by_user_id) REFERENCES users (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_approvals_resolved_by_user_id_users FOREIGN KEY(resolved_by_user_id) REFERENCES users (id) ON DELETE SET NULL\n);")
        op.execute("CREATE INDEX ix_approvals_run_status ON approvals (run_id, status);")
        op.execute("CREATE TABLE documents (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tsource_id UUID, \n\texternal_id TEXT, \n\ttitle TEXT, \n\tpath TEXT, \n\tdoc_type VARCHAR(64) NOT NULL, \n\tsource_type VARCHAR(64), \n\tchecksum VARCHAR(128), \n\tcontent_hash VARCHAR(128), \n\tmodified_at TIMESTAMP WITH TIME ZONE, \n\tsize_bytes INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_documents PRIMARY KEY (id), \n\tCONSTRAINT uq_documents_project_source_external_id UNIQUE (project_id, source_id, external_id), \n\tCONSTRAINT fk_documents_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_documents_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (id) ON DELETE SET NULL\n);")
        op.execute("CREATE INDEX ix_documents_project_id ON documents (project_id);")
        op.execute("CREATE INDEX ix_documents_project_source_external ON documents (project_id, source_id, external_id);")
        op.execute("CREATE INDEX ix_documents_project_source_type ON documents (project_id, source_type);")
        op.execute("CREATE INDEX ix_documents_source_id ON documents (source_id);")
        op.execute("CREATE TABLE eval_run_cases (\n\tid UUID NOT NULL, \n\teval_run_id UUID NOT NULL, \n\tcase_id VARCHAR(128) NOT NULL, \n\tquestion TEXT NOT NULL, \n\tresult_json JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_eval_run_cases PRIMARY KEY (id), \n\tCONSTRAINT uq_eval_run_cases_eval_case UNIQUE (eval_run_id, case_id), \n\tCONSTRAINT fk_eval_run_cases_eval_run_id_eval_runs FOREIGN KEY(eval_run_id) REFERENCES eval_runs (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_eval_run_cases_eval_id ON eval_run_cases (eval_run_id);")
        op.execute("CREATE TABLE incident_report_drafts (\n\tid UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\tcontent_markdown TEXT NOT NULL, \n\tcontent_json JSONB, \n\tstatus draftstatus NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_incident_report_drafts PRIMARY KEY (id), \n\tCONSTRAINT fk_incident_report_drafts_run_id_agent_runs FOREIGN KEY(run_id) REFERENCES agent_runs (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_incident_report_drafts_run_id ON incident_report_drafts (run_id);")
        op.execute("CREATE TABLE issue_drafts (\n\tid UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tbody_markdown TEXT NOT NULL, \n\tprovider VARCHAR(64) NOT NULL, \n\tstatus draftstatus NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_issue_drafts PRIMARY KEY (id), \n\tCONSTRAINT fk_issue_drafts_run_id_agent_runs FOREIGN KEY(run_id) REFERENCES agent_runs (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_issue_drafts_run_id ON issue_drafts (run_id);")
        op.execute("CREATE TABLE operational_events (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\toperational_run_id UUID, \n\tcategory VARCHAR(64) NOT NULL, \n\tevent_type VARCHAR(96) NOT NULL, \n\tseverity VARCHAR(16) NOT NULL, \n\tpayload_json JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_operational_events PRIMARY KEY (id), \n\tCONSTRAINT fk_operational_events_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_operational_events_operational_run_id_operational_runs FOREIGN KEY(operational_run_id) REFERENCES operational_runs (id) ON DELETE SET NULL\n);")
        op.execute("CREATE INDEX ix_operational_events_category_created ON operational_events (category, created_at);")
        op.execute("CREATE INDEX ix_operational_events_project_created ON operational_events (project_id, created_at);")
        op.execute("CREATE INDEX ix_operational_events_run ON operational_events (operational_run_id);")
        op.execute("CREATE TABLE operational_findings (\n\tid UUID NOT NULL, \n\toperational_run_id UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tfinding_type VARCHAR(96) NOT NULL, \n\tseverity VARCHAR(16) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tevidence_json JSONB, \n\tthreshold_json JSONB, \n\trecommended_action TEXT NOT NULL, \n\tfingerprint VARCHAR(128) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_operational_findings PRIMARY KEY (id), \n\tCONSTRAINT fk_operational_findings_operational_run_id_operational_runs FOREIGN KEY(operational_run_id) REFERENCES operational_runs (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_operational_findings_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_operational_findings_project_created ON operational_findings (project_id, created_at);")
        op.execute("CREATE INDEX ix_operational_findings_project_severity ON operational_findings (project_id, severity);")
        op.execute("CREATE INDEX ix_operational_findings_run ON operational_findings (operational_run_id);")
        op.execute("CREATE TABLE source_syncs (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tsource_id UUID NOT NULL, \n\tcollector_id UUID, \n\tstatus VARCHAR(64) NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tfiles_seen INTEGER NOT NULL, \n\tdocuments_received INTEGER NOT NULL, \n\tchunks_created INTEGER NOT NULL, \n\tfiles_skipped INTEGER NOT NULL, \n\tparser_errors INTEGER NOT NULL, \n\tcoverage_json JSONB, \n\tdiagnostics_json JSONB, \n\terror_message TEXT, \n\tCONSTRAINT pk_source_syncs PRIMARY KEY (id), \n\tCONSTRAINT fk_source_syncs_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_source_syncs_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_source_syncs_collector_id_collectors FOREIGN KEY(collector_id) REFERENCES collectors (id) ON DELETE SET NULL\n);")
        op.execute("CREATE INDEX ix_source_syncs_project_id ON source_syncs (project_id);")
        op.execute("CREATE INDEX ix_source_syncs_source_started ON source_syncs (source_id, started_at);")
        op.execute("CREATE TABLE chunks (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tdocument_id UUID NOT NULL, \n\tsource_id UUID, \n\tchunk_type VARCHAR(64) NOT NULL, \n\tservice_name VARCHAR(256), \n\tendpoint TEXT, \n\tdeploy_hash VARCHAR(128), \n\ttimestamp_start TIMESTAMP WITH TIME ZONE, \n\ttimestamp_end TIMESTAMP WITH TIME ZONE, \n\tsection_title TEXT, \n\tstart_line INTEGER, \n\tend_line INTEGER, \n\ttext TEXT NOT NULL, \n\ttoken_count INTEGER, \n\tmetadata_json JSONB, \n\tsearch_tsvector TSVECTOR, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_chunks PRIMARY KEY (id), \n\tCONSTRAINT fk_chunks_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_chunks_document_id_documents FOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_chunks_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (id) ON DELETE SET NULL\n);")
        op.execute("CREATE INDEX ix_chunks_chunk_type ON chunks (chunk_type);")
        op.execute("CREATE INDEX ix_chunks_deploy_hash ON chunks (deploy_hash);")
        op.execute("CREATE INDEX ix_chunks_document_id ON chunks (document_id);")
        op.execute("CREATE INDEX ix_chunks_endpoint ON chunks (endpoint);")
        op.execute("CREATE INDEX ix_chunks_project_deploy_hash ON chunks (project_id, deploy_hash);")
        op.execute("CREATE INDEX ix_chunks_project_id ON chunks (project_id);")
        op.execute("CREATE INDEX ix_chunks_project_service_endpoint ON chunks (project_id, service_name, endpoint);")
        op.execute("CREATE INDEX ix_chunks_project_source_type ON chunks (project_id, source_id, chunk_type);")
        op.execute("CREATE INDEX ix_chunks_project_timestamp_start ON chunks (project_id, timestamp_start);")
        op.execute("CREATE INDEX ix_chunks_search_tsvector ON chunks USING gin (search_tsvector);")
        op.execute("CREATE INDEX ix_chunks_service_name ON chunks (service_name);")
        op.execute("CREATE INDEX ix_chunks_source_id ON chunks (source_id);")
        op.execute("CREATE INDEX ix_chunks_timestamp_end ON chunks (timestamp_end);")
        op.execute("CREATE INDEX ix_chunks_timestamp_start ON chunks (timestamp_start);")
        op.execute("CREATE TABLE index_jobs (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tsource_id UUID NOT NULL, \n\tsync_id UUID, \n\tnormalized_payload_json JSONB NOT NULL, \n\tcontent_hash VARCHAR(128) NOT NULL, \n\tindex_version VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tattempts INTEGER NOT NULL, \n\terror_code VARCHAR(64), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tqueued_at TIMESTAMP WITH TIME ZONE, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tCONSTRAINT pk_index_jobs PRIMARY KEY (id), \n\tCONSTRAINT fk_index_jobs_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_index_jobs_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_index_jobs_sync_id_source_syncs FOREIGN KEY(sync_id) REFERENCES source_syncs (id) ON DELETE SET NULL\n);")
        op.execute("CREATE INDEX ix_index_jobs_source_version ON index_jobs (source_id, index_version);")
        op.execute("CREATE INDEX ix_index_jobs_status_created ON index_jobs (status, created_at);")
        op.execute("CREATE INDEX ix_index_jobs_status_queued ON index_jobs (status, queued_at);")
        op.execute("CREATE INDEX ix_index_jobs_sync_id ON index_jobs (sync_id);")
        op.execute("CREATE TABLE evidence_relations (\n\tid UUID NOT NULL, \n\tproject_id UUID NOT NULL, \n\tevidence_chunk_id UUID NOT NULL, \n\trelation_type VARCHAR(64) NOT NULL, \n\tfrom_key VARCHAR(512) NOT NULL, \n\tto_key VARCHAR(512) NOT NULL, \n\tmetadata_json JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_evidence_relations PRIMARY KEY (id), \n\tCONSTRAINT uq_evidence_relations_edge UNIQUE (project_id, evidence_chunk_id, relation_type, from_key, to_key), \n\tCONSTRAINT fk_evidence_relations_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_evidence_relations_evidence_chunk_id_chunks FOREIGN KEY(evidence_chunk_id) REFERENCES chunks (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_evidence_relations_project_from ON evidence_relations (project_id, from_key);")
        op.execute("CREATE INDEX ix_evidence_relations_project_to ON evidence_relations (project_id, to_key);")
        op.execute("CREATE INDEX ix_evidence_relations_project_type ON evidence_relations (project_id, relation_type);")
        op.execute("CREATE TABLE retrieval_results (\n\tid UUID NOT NULL, \n\tretrieval_run_id UUID NOT NULL, \n\tchunk_id UUID NOT NULL, \n\tvector_score FLOAT, \n\tlexical_score FLOAT, \n\tfused_score FLOAT, \n\trerank_score FLOAT, \n\trank INTEGER, \n\tCONSTRAINT pk_retrieval_results PRIMARY KEY (id), \n\tCONSTRAINT fk_retrieval_results_retrieval_run_id_retrieval_runs FOREIGN KEY(retrieval_run_id) REFERENCES retrieval_runs (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_retrieval_results_chunk_id_chunks FOREIGN KEY(chunk_id) REFERENCES chunks (id) ON DELETE CASCADE\n);")
        op.execute("CREATE INDEX ix_retrieval_results_run_id ON retrieval_results (retrieval_run_id);")


def downgrade() -> None:
    # A V2 reset is intentionally all-or-nothing for an empty project.
    op.execute("DROP TABLE IF EXISTS retrieval_results CASCADE")
    op.execute("DROP TABLE IF EXISTS evidence_relations CASCADE")
    op.execute("DROP TABLE IF EXISTS operational_events CASCADE")
    op.execute("DROP TABLE IF EXISTS operational_findings CASCADE")
    op.execute("DROP TABLE IF EXISTS index_jobs CASCADE")
    op.execute("DROP TABLE IF EXISTS chunks CASCADE")
    op.execute("DROP TABLE IF EXISTS source_syncs CASCADE")
    op.execute("DROP TABLE IF EXISTS eval_run_cases CASCADE")
    op.execute("DROP TABLE IF EXISTS eval_runs CASCADE")
    op.execute("DROP TABLE IF EXISTS issue_drafts CASCADE")
    op.execute("DROP TABLE IF EXISTS incident_report_drafts CASCADE")
    op.execute("DROP TABLE IF EXISTS approvals CASCADE")
    op.execute("DROP TABLE IF EXISTS agent_run_events CASCADE")
    op.execute("DROP TABLE IF EXISTS agent_runs CASCADE")
    op.execute("DROP TABLE IF EXISTS retrieval_runs CASCADE")
    op.execute("DROP TABLE IF EXISTS documents CASCADE")
    op.execute("DROP TABLE IF EXISTS collectors CASCADE")
    op.execute("DROP TABLE IF EXISTS sources CASCADE")
    op.execute("DROP TABLE IF EXISTS project_members CASCADE")
    op.execute("DROP TABLE IF EXISTS audit_events CASCADE")
    op.execute("DROP TABLE IF EXISTS operational_runs CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TABLE IF EXISTS projects CASCADE")
    op.execute("DROP TYPE IF EXISTS operationalrunstatus")
    op.execute("DROP TYPE IF EXISTS evalstatus")
    op.execute("DROP TYPE IF EXISTS draftstatus")
    op.execute("DROP TYPE IF EXISTS approvalstatus")
    op.execute("DROP TYPE IF EXISTS runstatus")
    op.execute("DROP TYPE IF EXISTS projectrole")
